//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KyrsovayaAvtoservise.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class manufacturer_a_import
    {
        public string Название_производителя { get; set; }
        public System.DateTime Дата_начала_работы { get; set; }
    }
}
